#redirects to home.html
--- 
plugins:
  - jekyll-redirect-from
redirect_to: "https://www.junglebooklegion.com/home.html"
---

theme: jekyll-theme-hacker
layout: default
title: Jungle Book Legion
description: base domain, check out our github
